/*Banco de dados para uma livraria*/
/*CRIA O BANCO LIVRARIA*/
CREATE DATABASE LIVRARIA;
USE LIVRARIA;

/*CRIA A TABELA LIVROS*/
CREATE TABLE LIVROS(
ID INTEGER (2),
NOME_DO_LIVRO VARCHAR(50),	
NOME_DO_AUTOR VARCHAR(30),
SEXO VARCHAR(10),
NUMERO_DE_PÁGINAS VARCHAR(10),
NOME_DA_EDITORA VARCHAR(30),
VALOR FLOAT(5,2),
ESTADO_EDITORA CHAR(2),
ANO_PUBLICACAO CHAR(4)
);

/*MOSTRAR TODAS TABELAS CRIADA */
SHOW TABLES

/*INSERIR DADOS NAS TABELAS*/
INSERT INTO LIVROS VALUES(1,'Cavaleiro Real', 'Ana Claudia', 'Feminino','465','Atlas', 49.9,'RJ','2009');
INSERT INTO LIVROS VALUES(2,'SQL para leigos','João Nunes',	'Masculino','450','Addison',98,'SP','2018');
INSERT INTO LIVROS VALUES(3,'Receitas Caseiras','Celia Tavares','Feminino','210','Atlas',45,'RJ','2008');
INSERT INTO LIVROS VALUES(4,'Pessoas Efetivas','Eduardo Santos','Masculino','390','Beta',78.99,'RJ','2018');
INSERT INTO LIVROS VALUES(5,'Habitos Saudáveis','Eduardo Santos','Masculino','630','Beta',150.98,'RJ','2019');
INSERT INTO LIVROS VALUES(6,'A Casa Marrom','Hermes Macedo','Masculino','250','Bubba',60,'MG','2016');
INSERT INTO LIVROS VALUES(7,'Estacio Querido','Geraldo Francisco','Masculino','310','Insignia',100,'ES','2015');
INSERT INTO LIVROS VALUES(8,'Pra sempre amigas','Leda Silva','Feminino','510','Insignia',78.98,'ES','2011');
INSERT INTO LIVROS VALUES(9,'Copas Inesqueciveis','Marco Alcantara','Masculino','200','Larson',130.98,'RS','2018');
INSERT INTO LIVROS VALUES(10,'O poder da mente','Clara Mafra','Feminino','120','Continental',56.58,'SP','2017');

/*TRAZER TODOS OS DADOS*/
SELECT * FROM LIVROS;

/*TRAZER O NOME DO LIVRO E DA EDITORA*/
SELECT NOME_DO_LIVRO, NOME_DA_EDITORA FROM LIVROS;

/*TRAZER O NOME DO LIVRO A UF E OS LIVROS PUBLICADOS PELO SEXO MASCULINO*/
SELECT NOME_DO_LIVRO, ESTADO_EDITORA FROM LIVROS
WHERE SEXO = 'Masculino';

/*TRAZER O NOME DO LIVRO NUMERO DE PAGINAS E PUBLICADOS POR SEXO FEMININO*/
SELECT NOME_DO_LIVRO, NUMERO_DE_PÁGINAS FROM LIVROS
WHERE SEXO = 'Feminino';

/*VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO*/
SELECT VALOR FROM LIVROS
WHERE ESTADO_EDITORA = 'SP';

/*DADOS DOS AUTORES DO SEXO MASCULINO PUBLICADOS POR SAO PAULO OU RIO*/
SELECT * FROM LIVROS
WHERE SEXO = 'Masculino'
AND ESTADO_EDITORA = 'SP'
OR ESTADO_EDITORA = 'RJ';


